version: '3'
# TODO consider setting hostnames to have lcl prefix
services:
#  irods:
#    build:
#      context: .
#      dockerfile: Dockerfile-irods
#    container_name: irods
#    hostname: irods
#    volumes:
#      - .:/hydroshare
#    # the following two lines allow docker exec -it <container name> /bin/bash to attach to container
#    stdin_open: true
#    tty: true
  postgis:
    build:
      context: .
      dockerfile: Dockerfile-postgis
    container_name: postgis
    hostname: postgis
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
  redis:
    image: redis:2.8
    container_name: redis
#  rabbitmq:
#    image: rabbitmq:3.5
#    container_name: rabbitmq
  solr:
    image: solr:6.6
    container_name: solr
    volumes:
      - .:/hydroshare
    command: [sh, -c, /bin/bash /opt/solr/bin/solr -f]
  hydroshare:
    build:
      context: .
      dockerfile: Dockerfile-hydroshare
    container_name: hydroshare
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    privileged: true
    # used to have a sleep 3 will need to tie the dependency to deeper service check on postgis for now seems to be ok
    depends_on:
      - postgis
#      - irods
      - redis
#      - rabbitmq
      - solr
    environment:
      POSTGIS_HOST: postgis
      POSTGIS_PORT_5432_TCP_ADDR: postgis
      POSTGIS_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      POSTGIS_USER: postgres
      PGPASSWORD: postgres
      SOLR_HOST: solr
      TMP: /hs_tmp
#      HOST_SSL_DIR: /Users/mobrien/hydro/hs-certs
      HS_DATABASE: pg.development.sql
#      HS_LOG_FILES: /Users/mobrien/hydro/hydroshare/log
      HS_SERVICE_UID: 1000
      HS_SERVICE_GID: 1000
    volumes:
      # hydroshare repository
      - .:/hydroshare
      # pycharm debugging
      # - "/home/hydro/pycharm-debug:/pycharm-debug"
      # log files
      - "${LOGDIR}:/hydroshare/log"
      # shared location for gunicorn.sock between containers
      - "/hs_tmp"
      # temp directory shared with celery workers
      - "/shared_tmp"
    ports:
      - "1338:2022"
      - "8000:8000"
    links:
      - postgis:postgis
      - redis:redis
#      - rabbitmq:rabbitmq
      - solr:solr
    # the following two lines allow docker exec -it <container name> /bin/bash to attach to container
    stdin_open: true
    tty: true
#  defaultworker:
#    build:
#      context: .
#        dockerfile: Dockerfile-hydroshare
#    container_name: defaultworker
#    environment:
#      POSTGIS_HOST: postgis
#      POSTGIS_PORT_5432_TCP_ADDR: postgis
#      POSTGIS_PORT: 5432
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      POSTGIS_PASSWORD: postgres
#      POSTGIS_DB: postgres
#      PGPASSWORD: postgres
#      C_FORCE_ROOT: 1
#    volumes:
#      - .:/hydroshare
#      # - "/var/run/docker.sock:/docker.sock"
#    links:
#      - postgis:postgis
#      - redis:redis
#      - rabbitmq:rabbitmq
#    stdin_open: true
#    tty: true
#    command: /bin/bash init-defaultworker
